"""
Cross-Lingual Multilingual Lexicon & Inverted Index for all 20 NDAP Databases.
Provides vernacular synonyms across Hindi, Marathi, Bengali, Tamil, Telugu, and Hinglish.
Resolves the 20% schema-linking error from the IndicDB benchmark.
"""

from typing import Any, Dict

# Comprehensive Multilingual Synonyms mapped to exact NDAP table, column, and domain
NDAP_MULTILINGUAL_INDEX: Dict[str, Dict[str, Any]] = {
    # 1. PM-KISAN
    "pm_kisan_farmers": {
        "table": "ndap_pm_kisan_disbursement",
        "column": "farmer_beneficiaries",
        "data_type": "BIGINT",
        "synonyms": [
            "किसान",
            "शेतकरी",
            "రైతులు",
            "விவசாயிகள்",
            "কৃষক",
            "kisano",
            "kisan",
            "farmer",
            "farmers",
            "beneficiary",
            "beneficiaries",
            "पीएम-किसान",
            "పీఎం-కిసాన్",
        ],
    },
    "pm_kisan_amount": {
        "table": "ndap_pm_kisan_disbursement",
        "column": "amount_inr",
        "data_type": "DOUBLE",
        "synonyms": [
            "रुपये",
            "पैसे",
            "निधी",
            "रक्कम",
            "पैसा",
            "disburse",
            "disbursement",
            "amount",
            "నిధులు",
            "பணம்",
            "অর্থ",
            "টাকা",
            "fund",
            "funds",
        ],
    },
    # 2. Crop Production Census
    "crop_production": {
        "table": "ndap_crop_production_census",
        "column": "production_tonnes",
        "data_type": "DOUBLE",
        "synonyms": [
            "कापूस",
            "उत्पादन",
            "उत्पादनाचा",
            "टन",
            "पिक",
            "कापसाचे",
            "कापूस उत्पादन",
            "चावल",
            "ধান",
            "চাল",
            "উৎপাদন",
            "চাল উৎপাদন",
            "వరి",
            "పంట",
            "விளைச்சல்",
            "பயிர்",
            "production",
            "tonnes",
            "harvest",
            "crop",
            "crops",
            "yield",
        ],
    },
    # 3. Mandi Commodity Prices
    "mandi_prices": {
        "table": "ndap_mandi_commodity_prices",
        "column": "modal_price_inr",
        "data_type": "DOUBLE",
        "synonyms": [
            "मंडी",
            "भाव",
            "बाजार भाव",
            "किंमत",
            "દર",
            "ధర",
            "விலை",
            "দর",
            "mandi",
            "price",
            "prices",
            "rate",
            "wholesale",
            "commodity",
        ],
    },
    # 4. Fertilizer Distribution
    "fertilizer_sales": {
        "table": "ndap_fertilizer_distribution",
        "column": "sales_tonnes",
        "data_type": "DOUBLE",
        "synonyms": [
            "उर्वरक",
            "यूरिया",
            "खत",
            "विक्री",
            "बिक्री",
            "எரு",
            "உரம்",
            "ఎరువులు",
            "সার",
            "fertilizer",
            "urea",
            "dap",
            "sales",
            "distribution",
        ],
    },
    # 5. Soil Health Records
    "soil_health": {
        "table": "ndap_soil_health_records",
        "column": "soil_health_card_issued",
        "data_type": "BIGINT",
        "synonyms": [
            "मृदा स्वास्थ्य",
            "माती आरोग्य",
            "मृदा",
            "मண் வளம்",
            "నేల ఆరోగ్య",
            "মাটি",
            "soil",
            "soil health",
            "soil test",
        ],
    },
    # 6. Education Statistics
    "female_literacy": {
        "table": "ndap_education_stats",
        "column": "female_literacy_rate",
        "data_type": "FLOAT",
        "synonyms": [
            "महिला साक्षरता",
            "स्त्री साक्षरता",
            "महिला साक्षरता दर",
            "साक्षरता",
            "साक्षर",
            "female literacy",
            "female literacy rate",
            "saksharta",
            "literacy",
        ],
    },
    "student_count": {
        "table": "ndap_education_stats",
        "column": "student_count",
        "data_type": "INTEGER",
        "synonyms": [
            "विद्यार्थी",
            "छात्र",
            "विद्यार्थी संख्या",
            "மாணவர்",
            "విద్యార్థులు",
            "vidyarthi",
            "student",
            "students",
            "enrollment",
        ],
    },
    # 7. School Infrastructure
    "computer_labs": {
        "table": "ndap_school_infrastructure",
        "column": "schools_with_computer_labs",
        "data_type": "INTEGER",
        "synonyms": [
            "संगणक",
            "संगणक प्रयोगशाळा",
            "कंप्यूटर",
            "प्रयोगशाला",
            "கணினி",
            "கம்ப்யூட்டர்",
            "కంప్యూటర్",
            "কম্পিউটার",
            "computer lab",
            "computer labs",
            "labs",
            "schools",
        ],
    },
    # 8. Higher Education AISHE
    "higher_education_institutions": {
        "table": "ndap_higher_education_aishe",
        "column": "total_colleges",
        "data_type": "INTEGER",
        "synonyms": [
            "महाविद्यालय",
            "कॉलेज",
            "उच्च शिक्षण",
            "கல்லூரி",
            "కళాశాలలు",
            "কলেজ",
            "colleges",
            "universities",
            "aishe",
            "higher education",
        ],
    },
    # 9. Midday Meal Scheme
    "midday_meal_beneficiaries": {
        "table": "ndap_midday_meal_scheme",
        "column": "primary_students_benefited",
        "data_type": "BIGINT",
        "synonyms": [
            "मिड-डे मील",
            "माध्यान्ह भोजन",
            "माध्यान्ह",
            "মিড-ডে মিল",
            "মিড ডে মিল",
            "উপকৃত",
            "மதிய உணவு",
            "మధ్యాహ్న భోజనం",
            "midday meal",
            "mid day meal",
            "meal",
        ],
    },
    # 10. Vocational Skill Training
    "skill_training": {
        "table": "ndap_vocational_skill_training",
        "column": "certified_candidates",
        "data_type": "BIGINT",
        "synonyms": [
            "कौशल विकास",
            "कौशल्य प्रशिक्षण",
            "प्रमाणित",
            "திறன் பயிற்சி",
            "నైపుణ్య శిక్షణ",
            "দক্ষতা",
            "skill",
            "training",
            "vocational",
            "pmkvy",
        ],
    },
    # 11. NFHS-5 Health Indicators
    "institutional_births": {
        "table": "ndap_nfhs5_health_indicators",
        "column": "institutional_births_pct",
        "data_type": "FLOAT",
        "synonyms": [
            "संस्थागत प्रसव",
            "संस्थात्मक प्रसूती",
            "nfhs",
            "மருத்துவமனை பிரசவம்",
            "ఆసుపత్రి కాన్పులు",
            "institutional births",
            "births",
        ],
    },
    # 12. Rural Health Infrastructure
    "health_subcentres": {
        "table": "ndap_rural_health_infrastructure",
        "column": "phc_count",
        "data_type": "INTEGER",
        "synonyms": [
            "प्राथमिक आरोग्य केंद्र",
            "पीएचसी",
            "स्वास्थ्य केंद्र",
            "ஆரம்ப சுகாதார நிலையம்",
            "ప్రాథమిక ఆరోగ్య కేంద్రం",
            "স্বাস্থ্য কেন্দ্র",
            "phc",
            "health centre",
        ],
    },
    # 13. Maternal & Child Mortality
    "maternal_mortality": {
        "table": "ndap_maternal_child_mortality",
        "column": "mmr_per_100k_births",
        "data_type": "FLOAT",
        "synonyms": [
            "मातृ मृत्यु दर",
            "माता मृत्यू दर",
            "ശിശു മരണം",
            "মাতৃমৃত্যু",
            "தாய் இறப்பு விகிதம்",
            "తల్లుల మరణాల రేటు",
            "mmr",
            "maternal mortality",
        ],
    },
    # 14. Ayushman Bharat PM-JAY
    "ayushman_cards": {
        "table": "ndap_ayushman_bharat_pmjay",
        "column": "cards_issued",
        "data_type": "BIGINT",
        "synonyms": [
            "आयुष्मान भारत",
            "आयुष्मान",
            "कार्ड",
            "कार्ड जारी",
            "पीएमजेएवाई",
            "pmjay",
            "ஆயுஷ்மான் பாரத்",
            "ఆయుష్మాన్ భారత్",
            "আয়ুষ্মান ভারত",
            "ayushman",
            "golden card",
        ],
    },
    # 15. National TB Portal
    "tb_notifications": {
        "table": "ndap_national_tuberculosis_portal",
        "column": "notified_tb_patients",
        "data_type": "BIGINT",
        "synonyms": [
            "क्षयरोग",
            "टीबी",
            "निक्षय",
            "காசநோய்",
            "క్షయవ్యాధి",
            "যক্ষ্মা",
            "tb",
            "tuberculosis",
            "nikshay",
        ],
    },
    # 16. MGNREGA Employment
    "mgnrega_mandays": {
        "table": "mgnrega_state_annual_employment",
        "column": "total_mandays_generated",
        "data_type": "BIGINT",
        "synonyms": [
            "मनरेगा",
            "कार्य दिवस",
            "रोजगार",
            "कामकाज",
            "mandays",
            "mgnrega",
            "மனித வேலை நாட்கள்",
            "வேலை உறுதி",
            "మహాత్మా గాంధీ గ్రామీణ ఉపాధి",
            "ఉపాధి హామీ",
            "কাজের দিন",
            "কর্মসংস্থান",
            "nrega",
        ],
    },
    # 17. PMGSY Rural Roads
    "pmgsy_roads": {
        "table": "ndap_pmgsy_rural_roads",
        "column": "completed_road_length_km",
        "data_type": "DOUBLE",
        "synonyms": [
            "पीएमजीएसवाई",
            "सड़क",
            "रस्ते",
            "रोड",
            "ரவாண்டா",
            "சாலைகள்",
            "சாலை",
            "పీఎంజీఎస్వై",
            "రోడ్ల",
            "రోడ్ల పొడవు",
            "রাস্তা",
            "pmgsy",
            "rural road",
            "road length",
        ],
    },
    # 18. Jal Jeevan Tap Water
    "tap_water_connections": {
        "table": "ndap_jal_jeevan_tap_water",
        "column": "households_with_tap_connection",
        "data_type": "BIGINT",
        "synonyms": [
            "जल जीवन",
            "नल से जल",
            "नळ जोडणी",
            "कुडीनीर",
            "குடிநீர் குழாய்",
            "குடிநீர்",
            "మంచినీటి కుళాయి",
            "జల జీవన్",
            "ট্যাপের জল",
            "জল জীবন",
            "jal jeevan",
            "tap water",
            "tap connection",
        ],
    },
    # 19. PMAY Rural Housing
    "pmay_houses": {
        "table": "ndap_pmay_rural_housing",
        "column": "houses_completed",
        "data_type": "BIGINT",
        "synonyms": [
            "पीएमएवाई",
            "आवास योजना",
            "घर",
            "पक्के मकान",
            "pucca houses",
            "houses",
            "வீடுகள்",
            "గ్రామీణ గృహాలు",
            "గృహ నిర్మాణం",
            "আবাস যোজনা",
            "বাড়ি",
            "pmay",
            "housing",
        ],
    },
    # 20. Gram Panchayat Finance
    "panchayat_grants": {
        "table": "ndap_gram_panchayat_finance",
        "column": "central_finance_grant_inr",
        "data_type": "DOUBLE",
        "synonyms": [
            "ग्राम पंचायत",
            "पंचायत",
            "वित्त आयोग",
            "अनुदान",
            "கிராம பஞ்சாயத்து",
            "గ్రామ పంచాయతీ",
            "গ্রাম পঞ্চায়েত",
            "panchayat",
            "finance grant",
        ],
    },
}
